"""Seed sample households into the database."""

from datetime import date

from app.constants import PovertyStatus
from app.database import SessionLocal
from app.models import Household


SAMPLES = [
    {
        "household_code": "HH-0001",
        "head_name": "Nguyễn Thị Hoa",
        "birth_date": date(1985, 3, 12),
        "gender": "Nữ",
        "id_card": "031234567890",
        "province": "TP. Hà Nội",
        "district": "Ba Đình",
        "commune": "Phường Ngọc Hà",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Kinh",
        "members_count": 4,
        "income_per_capita": 1200000,
        "score_b1": 68,
        "score_b2": 74,
        "note": "Thiếu điều kiện tiếp cận giáo dục và y tế.",
        "area": "Thành thị",
        "village": "Tổ 5",
        "officer": "Trần Văn Minh",
        "remark": "Đã khảo sát thực địa.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 12, 1),
    },
    {
        "household_code": "HH-0002",
        "head_name": "Phạm Văn Long",
        "birth_date": date(1979, 7, 24),
        "gender": "Nam",
        "id_card": "038765432109",
        "province": "TP. Hải Phòng",
        "district": "Lê Chân",
        "commune": "Phường An Biên",
        "poverty_status": PovertyStatus.NEAR_POOR,
        "ethnicity": "Kinh",
        "members_count": 5,
        "income_per_capita": 1500000,
        "score_b1": 55,
        "score_b2": 61,
        "note": "Thu nhập sát chuẩn, thiếu việc làm ổn định.",
        "area": "Thành thị",
        "village": "Tổ 9",
        "officer": "Nguyễn Thị Ngọc",
        "remark": "Cần hỗ trợ vay vốn.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 11, 15),
    },
    {
        "household_code": "HH-0003",
        "head_name": "Lê Văn Nam",
        "birth_date": date(1990, 5, 2),
        "gender": "Nam",
        "id_card": "012345678901",
        "province": "TP. Đà Nẵng",
        "district": "Hải Châu",
        "commune": "Phường Thạch Thang",
        "poverty_status": PovertyStatus.AT_RISK,
        "ethnicity": "Kinh",
        "members_count": 3,
        "income_per_capita": 1800000,
        "score_b1": 42,
        "score_b2": 49,
        "note": "Nguy cơ tái nghèo do việc làm không ổn định.",
        "area": "Thành thị",
        "village": "Khu phố 2",
        "officer": "Lê Thị Hạnh",
        "remark": "Theo dõi biến động thu nhập.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 10, 20),
    },
    {
        "household_code": "HH-0004",
        "head_name": "Hoàng Thị Lan",
        "birth_date": date(1982, 9, 19),
        "gender": "Nữ",
        "id_card": "024681357913",
        "province": "Nghệ An",
        "district": "Quỳnh Lưu",
        "commune": "Xã Quỳnh Hồng",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Thái",
        "members_count": 6,
        "income_per_capita": 900000,
        "score_b1": 77,
        "score_b2": 80,
        "note": "Thiếu đất sản xuất, nhiều người phụ thuộc.",
        "area": "Nông thôn",
        "village": "Xóm 7",
        "officer": "Phan Văn Dũng",
        "remark": "Ưu tiên hỗ trợ sinh kế.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 9, 30),
    },
    {
        "household_code": "HH-0005",
        "head_name": "Trần Văn Minh",
        "birth_date": date(1975, 1, 8),
        "gender": "Nam",
        "id_card": "099887766554",
        "province": "Lâm Đồng",
        "district": "Di Linh",
        "commune": "Xã Đinh Lạc",
        "poverty_status": PovertyStatus.ESCAPED,
        "ethnicity": "K'Ho",
        "members_count": 4,
        "income_per_capita": 2300000,
        "score_b1": 35,
        "score_b2": 40,
        "note": "Đã thoát nghèo, cần theo dõi ổn định.",
        "area": "Nông thôn",
        "village": "Thôn 3",
        "officer": "Võ Thị Liên",
        "remark": "Theo dõi định kỳ.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 8, 25),
    },
    {
        "household_code": "HH-0006",
        "head_name": "Đặng Văn Khánh",
        "birth_date": date(1988, 2, 14),
        "gender": "Nam",
        "id_card": "078901234567",
        "province": "TP. Hồ Chí Minh",
        "district": "Bình Thạnh",
        "commune": "Phường 14",
        "poverty_status": PovertyStatus.NEAR_POOR,
        "ethnicity": "Kinh",
        "members_count": 3,
        "income_per_capita": 1700000,
        "score_b1": 50,
        "score_b2": 58,
        "note": "Việc làm thời vụ, thu nhập không ổn định.",
        "area": "Thành thị",
        "village": "Khu phố 6",
        "officer": "Phạm Thị Mai",
        "remark": "Khuyến nghị hỗ trợ nghề.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 12, 12),
    },
    {
        "household_code": "HH-0007",
        "head_name": "Võ Thị Hạnh",
        "birth_date": date(1992, 11, 5),
        "gender": "Nữ",
        "id_card": "066778899001",
        "province": "TP. Cần Thơ",
        "district": "Ninh Kiều",
        "commune": "Phường An Khánh",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Kinh",
        "members_count": 5,
        "income_per_capita": 980000,
        "score_b1": 72,
        "score_b2": 78,
        "note": "Thiếu điều kiện học tập cho con.",
        "area": "Thành thị",
        "village": "Tổ 12",
        "officer": "Lê Văn Hòa",
        "remark": "Cần hỗ trợ học phí.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 11, 3),
    },
    {
        "household_code": "HH-0008",
        "head_name": "Ngô Văn Tuấn",
        "birth_date": date(1980, 4, 21),
        "gender": "Nam",
        "id_card": "055443322110",
        "province": "Thanh Hóa",
        "district": "Triệu Sơn",
        "commune": "Xã Dân Lý",
        "poverty_status": PovertyStatus.AT_RISK,
        "ethnicity": "Kinh",
        "members_count": 6,
        "income_per_capita": 1300000,
        "score_b1": 48,
        "score_b2": 52,
        "note": "Nguy cơ tái nghèo do thiên tai.",
        "area": "Nông thôn",
        "village": "Thôn 2",
        "officer": "Đỗ Thị Hằng",
        "remark": "Theo dõi mùa vụ.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 10, 5),
    },
    {
        "household_code": "HH-0009",
        "head_name": "Phan Văn Dũng",
        "birth_date": date(1972, 6, 30),
        "gender": "Nam",
        "id_card": "044556677889",
        "province": "Quảng Nam",
        "district": "Thăng Bình",
        "commune": "Xã Bình Dương",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Cơ Tu",
        "members_count": 7,
        "income_per_capita": 850000,
        "score_b1": 81,
        "score_b2": 86,
        "note": "Thiếu sinh kế ổn định.",
        "area": "Nông thôn",
        "village": "Thôn 4",
        "officer": "Nguyễn Văn Quang",
        "remark": "Ưu tiên hỗ trợ sinh kế.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 9, 18),
    },
    {
        "household_code": "HH-0010",
        "head_name": "Bùi Thị Thu",
        "birth_date": date(1987, 8, 9),
        "gender": "Nữ",
        "id_card": "033221100998",
        "province": "Khánh Hòa",
        "district": "Nha Trang",
        "commune": "Phường Vĩnh Hòa",
        "poverty_status": PovertyStatus.NEAR_POOR,
        "ethnicity": "Kinh",
        "members_count": 4,
        "income_per_capita": 1600000,
        "score_b1": 53,
        "score_b2": 57,
        "note": "Thu nhập thấp, thiếu bảo hiểm y tế.",
        "area": "Thành thị",
        "village": "Tổ 3",
        "officer": "Phạm Văn Đức",
        "remark": "Hỗ trợ BHYT.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 8, 10),
    },
    {
        "household_code": "HH-0011",
        "head_name": "Trịnh Văn Hậu",
        "birth_date": date(1995, 12, 1),
        "gender": "Nam",
        "id_card": "022334455667",
        "province": "Bắc Ninh",
        "district": "Yên Phong",
        "commune": "Xã Đông Phong",
        "poverty_status": PovertyStatus.ESCAPED,
        "ethnicity": "Kinh",
        "members_count": 3,
        "income_per_capita": 2100000,
        "score_b1": 30,
        "score_b2": 38,
        "note": "Đã thoát nghèo nhờ việc làm ổn định.",
        "area": "Nông thôn",
        "village": "Thôn Lý",
        "officer": "Nguyễn Thị Lan",
        "remark": "Theo dõi 2 năm.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 7, 22),
    },
    {
        "household_code": "HH-0012",
        "head_name": "Lưu Thị Bình",
        "birth_date": date(1983, 3, 3),
        "gender": "Nữ",
        "id_card": "088776655443",
        "province": "Đắk Lắk",
        "district": "Buôn Ma Thuột",
        "commune": "Phường Tân An",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Ê Đê",
        "members_count": 6,
        "income_per_capita": 920000,
        "score_b1": 79,
        "score_b2": 83,
        "note": "Thiếu nước sạch và nhà ở kiên cố.",
        "area": "Nông thôn",
        "village": "Buôn 1",
        "officer": "Y Bích",
        "remark": "Ưu tiên hỗ trợ nước sạch.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 6, 12),
    },
    {
        "household_code": "HH-0013",
        "head_name": "Hoàng Văn Sơn",
        "birth_date": date(1978, 1, 17),
        "gender": "Nam",
        "id_card": "077665544332",
        "province": "Lào Cai",
        "district": "Sa Pa",
        "commune": "Xã Tả Van",
        "poverty_status": PovertyStatus.AT_RISK,
        "ethnicity": "H'Mông",
        "members_count": 5,
        "income_per_capita": 1400000,
        "score_b1": 49,
        "score_b2": 55,
        "note": "Thu nhập bấp bênh do du lịch mùa vụ.",
        "area": "Nông thôn",
        "village": "Thôn Suối Hồ",
        "officer": "Sùng A Lử",
        "remark": "Hỗ trợ đào tạo nghề.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 5, 20),
    },
    {
        "household_code": "HH-0014",
        "head_name": "Đinh Thị Hường",
        "birth_date": date(1991, 9, 29),
        "gender": "Nữ",
        "id_card": "011223344556",
        "province": "Quảng Ngãi",
        "district": "Tư Nghĩa",
        "commune": "Xã Nghĩa Phương",
        "poverty_status": PovertyStatus.NEAR_POOR,
        "ethnicity": "Kinh",
        "members_count": 4,
        "income_per_capita": 1650000,
        "score_b1": 54,
        "score_b2": 60,
        "note": "Thiếu việc làm ổn định, cần hỗ trợ vay vốn.",
        "area": "Nông thôn",
        "village": "Thôn Trung",
        "officer": "Trần Văn Khoa",
        "remark": "Theo dõi sử dụng vốn.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 4, 2),
    },
    {
        "household_code": "HH-0015",
        "head_name": "Nguyễn Văn Phúc",
        "birth_date": date(1984, 12, 25),
        "gender": "Nam",
        "id_card": "099001122334",
        "province": "Phú Thọ",
        "district": "Việt Trì",
        "commune": "Phường Vân Cơ",
        "poverty_status": PovertyStatus.ESCAPED,
        "ethnicity": "Kinh",
        "members_count": 3,
        "income_per_capita": 2400000,
        "score_b1": 28,
        "score_b2": 35,
        "note": "Ổn định thu nhập, duy trì thoát nghèo.",
        "area": "Thành thị",
        "village": "Tổ 1",
        "officer": "Phan Thị Dung",
        "remark": "Theo dõi định kỳ.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 3, 18),
    },
    {
        "household_code": "HH-0016",
        "head_name": "Lâm Văn Hòa",
        "birth_date": date(1986, 6, 7),
        "gender": "Nam",
        "id_card": "066112233445",
        "province": "An Giang",
        "district": "Châu Phú",
        "commune": "Xã Bình Mỹ",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Kinh",
        "members_count": 6,
        "income_per_capita": 870000,
        "score_b1": 82,
        "score_b2": 88,
        "note": "Thiếu điều kiện nhà ở.",
        "area": "Nông thôn",
        "village": "Ấp 3",
        "officer": "Huỳnh Thị Hòa",
        "remark": "Đề xuất hỗ trợ nhà ở.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 2, 11),
    },
    {
        "household_code": "HH-0017",
        "head_name": "Phạm Thị Ánh",
        "birth_date": date(1993, 10, 10),
        "gender": "Nữ",
        "id_card": "055667788990",
        "province": "Đồng Nai",
        "district": "Biên Hòa",
        "commune": "Phường Tân Biên",
        "poverty_status": PovertyStatus.NEAR_POOR,
        "ethnicity": "Kinh",
        "members_count": 4,
        "income_per_capita": 1550000,
        "score_b1": 57,
        "score_b2": 62,
        "note": "Thiếu điều kiện y tế.",
        "area": "Thành thị",
        "village": "Khu phố 8",
        "officer": "Trương Văn Tín",
        "remark": "Hỗ trợ khám chữa bệnh.",
        "attachment_url": "",
        "last_surveyed_at": date(2024, 1, 14),
    },
    {
        "household_code": "HH-0018",
        "head_name": "Dương Văn Thái",
        "birth_date": date(1970, 4, 4),
        "gender": "Nam",
        "id_card": "044332211000",
        "province": "Ninh Bình",
        "district": "Hoa Lư",
        "commune": "Xã Ninh Vân",
        "poverty_status": PovertyStatus.AT_RISK,
        "ethnicity": "Kinh",
        "members_count": 5,
        "income_per_capita": 1350000,
        "score_b1": 46,
        "score_b2": 51,
        "note": "Nguy cơ tái nghèo do bệnh tật.",
        "area": "Nông thôn",
        "village": "Thôn Đồng",
        "officer": "Nguyễn Văn Huy",
        "remark": "Theo dõi sức khỏe.",
        "attachment_url": "",
        "last_surveyed_at": date(2023, 12, 28),
    },
    {
        "household_code": "HH-0019",
        "head_name": "Mai Thị Yến",
        "birth_date": date(1989, 5, 15),
        "gender": "Nữ",
        "id_card": "077889900112",
        "province": "Quảng Trị",
        "district": "Cam Lộ",
        "commune": "Xã Cam Tuyền",
        "poverty_status": PovertyStatus.POOR,
        "ethnicity": "Vân Kiều",
        "members_count": 6,
        "income_per_capita": 910000,
        "score_b1": 76,
        "score_b2": 81,
        "note": "Thiếu điều kiện nước sạch.",
        "area": "Nông thôn",
        "village": "Thôn 6",
        "officer": "Hồ Văn Nam",
        "remark": "Ưu tiên dự án nước sạch.",
        "attachment_url": "",
        "last_surveyed_at": date(2023, 11, 30),
    },
    {
        "household_code": "HH-0020",
        "head_name": "Trần Văn Hùng",
        "birth_date": date(1981, 2, 28),
        "gender": "Nam",
        "id_card": "066554433221",
        "province": "Bình Định",
        "district": "Phù Cát",
        "commune": "Xã Cát Hanh",
        "poverty_status": PovertyStatus.ESCAPED,
        "ethnicity": "Kinh",
        "members_count": 4,
        "income_per_capita": 2200000,
        "score_b1": 32,
        "score_b2": 39,
        "note": "Thoát nghèo ổn định, cần theo dõi.",
        "area": "Nông thôn",
        "village": "Thôn Đông",
        "officer": "Đặng Thị Lan",
        "remark": "Theo dõi 1 năm.",
        "attachment_url": "",
        "last_surveyed_at": date(2023, 10, 12),
    },
]


def seed_households() -> None:
    db = SessionLocal()
    try:
        db.query(Household).delete()
        for item in SAMPLES:
            db.add(Household(**item))
        db.commit()
        print("Inserted sample households.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_households()
